Enhacements Breadcrumbs, update docs.
yiisoft/yii-bulma pull request #51
Opened 2021-12-17 14:50 UTC by terabytesoftw

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌

- [x] Clean code.
- [x] Adjust Breadcrumbs template with icons. https://bulma.io/documentation/components/breadcrumb/#icons
- [x] Add more tests.
- [x] Update docs.

2021-12-17 19:21 UTC, samdark commented
Should we adjust demo somehow?

2021-12-17 19:28 UTC, terabytesoftw commented
> ¿Deberíamos ajustar la demo de alguna manera?

> Should we adjust demo somehow?

The demo has Bootstrap5 and the app doesn't use it.

2021-12-17 20:00 UTC, samdark requested changes

2021-12-17 20:17 UTC, terabytesoftw commented on src/Breadcrumbs.php
> +     * @return $this
done.

2021-12-17 20:18 UTC, terabytesoftw commented on src/Breadcrumbs.php
> +     * @return static
done.

2021-12-17 20:18 UTC, terabytesoftw commented on src/Breadcrumbs.php
> +     * @return static
done.

2021-12-17 20:18 UTC, terabytesoftw commented on src/Breadcrumbs.php
> +     * @return static
done.

2021-12-17 20:37 UTC, terabytesoftw commented on src/Breadcrumbs.php
> +    private function setId(): self
done.

2021-12-17 20:38 UTC, terabytesoftw commented on src/Breadcrumbs.php
> +        Html::addCssClass($new->attributes, 'breadcrumb');
done.

2021-12-17 20:39 UTC, terabytesoftw commented on src/Breadcrumbs.php
> +     * Set id of the widget.
done.

2021-12-17 20:40 UTC, terabytesoftw commented on src/Breadcrumbs.php
> +            $label = $icon . '<span>' . $label . '</span>';
https://bulma.io/documentation/components/breadcrumb/#icons it explicitly goes inside a <span> tag.

2021-12-17 20:48 UTC, samdark commented on src/Breadcrumbs.php
> +            $label = $icon . '<span>' . $label . '</span>';
Yes. But later you apply encoding and it will encode `<span>`.

2021-12-17 20:52 UTC, terabytesoftw commented on src/Breadcrumbs.php
> +            $label = $icon . '<span>' . $label . '</span>';
fixed, i use `Span::tag()`.

2021-12-21 21:49 UTC, samdark commented on src/Breadcrumbs.php
> +     * Returns a new instance with the specified item template.
```suggestion
     * Returns a new instance with the specified item HTML attributes.
```

2021-12-21 21:49 UTC, merged

2021-12-21 21:49 UTC, samdark commented
👍