Uplodad tests infection 100%.
yiisoft/yii-bulma pull request #61
Opened 2022-03-24 16:31 UTC by terabytesoftw

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌

2022-03-25 12:33 UTC, vjik requested changes

2022-03-25 12:33 UTC, vjik commented on src/NavBar.php
> +     * Returns a new instance with the specified aria-label attribute for the current element.
```suggestion
     * Returns a new instance with the specified `aria-label` attribute for the current element.
```

2022-03-25 12:33 UTC, vjik commented on src/ProgressBar.php
> +            $attributes['id'] = (Html::generateId($this->autoIdPrefix) . '-progressbar');
```suggestion
            $attributes['id'] = Html::generateId($this->autoIdPrefix) . '-progressbar';
```

2022-03-25 12:37 UTC, terabytesoftw commented on src/NavBar.php
> +     * Returns a new instance with the specified aria-label attribute for the current element.
done.

2022-03-25 12:38 UTC, terabytesoftw commented on src/ProgressBar.php
> +            $attributes['id'] = (Html::generateId($this->autoIdPrefix) . '-progressbar');
done.

2022-03-25 12:59 UTC, vjik approved these changes

2022-03-29 20:48 UTC, samdark approved these changes

2022-03-29 20:49 UTC, merged

2022-03-29 20:49 UTC, samdark commented
👍